# Generated by Django 6.0.5 on 2026-05-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='inventory_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
