# Generated by Django 6.0.5 on 2026-05-14 02:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookcopy_inventory_code'),
        ('circulation', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowtransaction',
            options={'ordering': ['-borrow_date']},
        ),
        migrations.AlterModelOptions(
            name='fine',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-reservation_date']},
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowtransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrowtransaction',
            name='borrowed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_borrow_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrowtransaction',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrowtransaction',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_transactions', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fine', to='circulation.borrowtransaction'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='books.book'),
        ),
        migrations.AddIndex(
            model_name='borrowtransaction',
            index=models.Index(fields=['status'], name='circulation_status_f111bb_idx'),
        ),
        migrations.AddIndex(
            model_name='borrowtransaction',
            index=models.Index(fields=['borrow_date'], name='circulation_borrow__38b6e2_idx'),
        ),
    ]
