# Generated by Django 6.0.5 on 2026-05-23 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookcopy_inventory_code'),
        ('circulation', '0002_alter_borrowtransaction_options_alter_fine_options_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowtransaction',
            name='book_copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_transactions', to='books.bookcopy'),
        ),
        migrations.CreateModel(
            name='BorrowPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('librarian', 'Librarian')], max_length=20)),
                ('max_books', models.PositiveIntegerField(default=3)),
                ('loan_days', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'unique_together': {('school', 'role')},
            },
        ),
    ]
