# Generated by Django 6.0.5 on 2026-05-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0003_alter_borrowtransaction_book_copy_borrowpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowtransaction',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
