# Generated by Django 6.0.5 on 2026-05-31 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0004_alter_borrowtransaction_due_date'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20),
        ),
    ]
